import * as z from 'zod'

export const heroSchema = z.object({
  headline: z.string().min(1, 'Headline is required'),
  headline_font_family: z.string().optional(),
  headline_font_size: z.string().optional(),
  headline_font_weight: z.string().optional(),
  headline_letter_spacing: z.string().optional(),
  headline_line_height: z.string().optional(),
  headline_color: z.string().optional(),
  subheadline: z.string().optional().or(z.literal('')),
  subheadline_font_family: z.string().optional(),
  subheadline_font_size: z.string().optional(),
  subheadline_font_weight: z.string().optional(),
  subheadline_line_height: z.string().optional(),
  subheadline_color: z.string().optional(),
  cta_text: z.string().optional().or(z.literal('')),
  cta_url: z.string().optional().or(z.literal('')),
  cta_font_family: z.string().optional(),
  cta_font_size: z.string().optional(),
  cta_font_weight: z.string().optional(),
  cta_letter_spacing: z.string().optional(),
  cta_bg_color: z.string().optional(),
  cta_hover_bg_color: z.string().optional(),
  cta_text_color: z.string().optional(),
  cta_border_radius: z.string().optional(),
  bg_type: z.enum(['gradient', 'image', 'video']).optional(),
  bg_gradient_start: z.string().optional(),
  bg_gradient_end: z.string().optional(),
  bg_image_url: z.string().url().optional().or(z.literal('')),
  bg_video_url: z.string().url().optional().or(z.literal('')),
})
